FROM fnndsc/ubuntu-python3

RUN mkdir rocketmq-client-python && chmod -R 777 rocketmq-client-python && \
    wget https://ons-client-sdk.oss-cn-hangzhou.aliyuncs.com/cpp-rpm/debian/cgo/rocketmq_2.0.0_amd64.deb && \
    dpkg -i rocketmq_2.0.0_amd64.deb && \
    pip install pytest pytest-timeout pytest-faulthandler pytest-cov codecov

COPY . rocketmq-client-python

WORKDIR rocketmq-client-python

RUN python setup.py install && \
    pip install -e .

